// <auto-generated />
namespace EFNorthwind.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class version13 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version13));
        
        string IMigrationMetadata.Id
        {
            get { return "201903151124123_version1.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
